### ISSUE TITLE
AttributeError: module 'googleapiclient' has no attribute '__version__'

### ISSUE THREAD

**Issue by edufresne** [GoogleCloudPlatform/cloud-debug-python#15] opened 2020-04-21 14:50 UTC
I am currently running app engine python3:7 environment and am getting errors in all requests going through my app. It fails on the import line to the `googleclouddebugger` library
```python
try:
    import googleclouddebugger

    googleclouddebugger.enable()
except ImportError:
    pass
```
requirements.txt
```
google-python-cloud-debugger
```
Stacktrace:
```
AttributeError: module 'googleapiclient' has no attribute '__version__'
at <module> (/env/lib/python3.7/site-packages/apiclient/__init__.py:22)
at <module> (/env/lib/python3.7/site-packages/googleclouddebugger/gcp_hub_client.py:33)
at <module> (/env/lib/python3.7/site-packages/googleclouddebugger/__init__.py:33)
at <module> (/srv/main.py:26)
```

**Comment by mctavish** [comment] 2020-04-21 18:21
It looks like this is caused by https://github.com/googleapis/google-api-python-client/issues/876

**Comment by edufresne** [comment] 2020-04-21 19:25
> It looks like this is caused by [googleapis/google-api-python-client#876](https://github.com/googleapis/google-api-python-client/issues/876)

Manually added `google-api-python-client==1.8.0` to `requirements.txt` fixes the issue. I'll create a PR for pinning the google-api-python-client dependency version to 1.8.0

**Comment by busunkim96** [comment] 2020-04-21 20:27
Hi! Dropping by since I saw you referenced https://github.com/googleapis/google-api-python-client/issues/876.

google-api-python-client 1.8.2 has been released and removes the problematic `googleapiclient.__version__` line. In addition, if you have any references to `apiclient` we recommend you replace them with `googleapiclient` instead.

**Comment by mctavish** [comment] 2020-04-22 16:27
I'm closing this issue because google-api-python-client 1.8.2 fixes the problem.

**Closed by mctavish** 2020-04-22 16:27 UTC
